services:
  p2-bank-api:
    image: 'pancake-bank-app'
    container_name: p2-deploy
    ports:
      - 7450:7450
    environment:
      - db_url=jdbc:postgresql://database-2.cjdho29bgj7p.us-east-1.rds.amazonaws.com/postgres
      - db_username=postgres
      - db_password=ragingbull
  prom:
    image: 'prom/prometheus'
    container_name: prom
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  graf:
    image: 'grafana/grafana'
    ports:
      - 8000:3000
