apiVersion: v1
kind: Service
metadata:
  name: pancake-lb
  namespace: pancake-controller-space
  labels:
    app: monitored-app
spec:
  type: LoadBalancer
  selector:
    app: monitored-app
  ports:
    - port: 80
      targetPort: 7070
      