global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'micrometer-example'
    metrics_path: '/prometheus'
    static_configs:
<<<<<<< HEAD
      - targets: ['']
=======
      - targets: ['p2-deploy:7070']
>>>>>>> ee4c30fe2cd1fffb71fb047b71ae96573962f143
