apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pancake-pvc
  namespace: pancake-controller-space
  labels:
    app: pancake-postgres

#ReadWriteOnce means that only a single application can read and write to this storage
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 5Mi
