apiVersion: apps/v1
kind: Deployment
metadata:
  name: pancake-controller-bank-app
  namespace: pancake-controller-space
  labels:
    app: pancake-bank-app
spec:
  selector:
    matchLabels:
      app: pancake-bank-app
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pancake-bank-app
    spec:
      containers:
      - name: pancake-bank-deployment
        image: revnkog/project2
        ports:
        - containerPort: 7070
        imagePullPolicy: Always
        env:
          - name: db_url
            value: jdbc:postgresql://pancake-postgres-service:5432/bank
          - name: db_user
            value: postgres
          - name: db_pass
            value: ragingbull

