apiVersion: apps/v1
kind: Deployment
metadata:
  name: pancake-controller-bank-app
  namespace: pancake-controller-space
  labels:
    app: pancake-bank-app
spec:
  selector:
    matchLabels:
      app: pancake-bank-app
  replicas: 3
  template:
    metadata:
      labels:
        app: pancake-bank-app
    spec:
      containers:
      - name: pancake-bank-deployment
        image: revnkog/project2
        ports:
        - containerPort: 7070
        imagePullPolicy: Always
        env:
          - name: db_url
            value: jdbc:postgresql://database-2.cjdho29bgj7p.us-east-1.rds.amazonaws.com/postgres
          - name: db_user
            value: postgres
          - name: db_pass
            value: ragingbull

